"stages":
- "test"
- "release"
"default":
  image:
    name: "openjdk:8u162"
  cache:
    paths:
    - "./gradle/wrapper"
    - "./gradle/caches"
  before_script:
  - "export GRADLE_USER_HOME=$(pwd)/.gradle"
"build":
  stage: "test"
  artifacts:
    when: "always"
    expire_in: "7 day"
    paths:
    - "build/test-results"
    - "build/reports"
    reports:
      junit:
      - "build/test-results/test/TEST-*.xml"
  script:
  - "./gradlew clean build"
"release":
  stage: "release"
  artifacts:
    when: "on_success"
    expire_in: "7 day"
    paths:
    - "build/libs"
  only:
    refs:
    - "master"
  script:
  - "./gradlew publishToMavenLocal"